/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praktikum;

import java.util.ArrayList;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;
    private ArrayList<String> profiles;
    

    @Override
    public void start(Stage primaryStage) {
        stage = primaryStage;
        profiles = new ArrayList<>();
        stage.setResizable(false);
        home();
        stage.show();
    }

    private void home() {
        Text nyapa = new Text("Halo Sobat Java");
        nyapa.setStyle("-fx-font-size: 25px; -fx-font-weight: bold; -fx-font-family: 'sansserif'; ");

        ImageView homeIcon = new ImageView(new Image("file:/home/lev/Downloads/homeicon.jpeg"));
        homeIcon.setFitWidth(150);
        homeIcon.setPreserveRatio(true);
        
        Button tambahProfile = new Button("+ Buat Profile");
        tambahProfile.setOnAction(e -> addProfile());
        tambahProfile.setPrefWidth(200);

        Button listProfile = new Button("Daftar Profile");
        listProfile.setOnAction(e -> profileScene());
        listProfile.setPrefWidth(200);

        VBox judul = new VBox(nyapa,homeIcon);
        judul.setAlignment(Pos.TOP_CENTER);
        judul.setPrefHeight(100);
        
        VBox homeScene = new VBox(10, judul, tambahProfile, listProfile);
        homeScene.setAlignment(Pos.CENTER);
        homeScene.setStyle("-fx-background-color: #c8a2c8;");
        
        
        stage.setScene(new Scene(homeScene, 400, 500));
        stage.setTitle("Naura App");
    }
    
    private void addProfile() {
        ImageView profileIcon = new ImageView(new Image("file:/home/lev/Downloads/tambahprofileIcon.png"));
        profileIcon.setFitWidth(100);
        profileIcon.setPreserveRatio(true);
    
        Label namaLabel = new Label("Nama: ");
        namaLabel.setStyle("-fx-font-size: 15px; -fx-font-weight: bold;");
        TextField textField = new TextField();
        textField.setPrefWidth(250);
    
        Label umurLabel = new Label("Umur: ");
        umurLabel.setStyle("-fx-font-size: 15px; -fx-font-weight: bold;");
        TextField umurField = new TextField();
        umurField.setPrefWidth(250);
    
        Label errorLabel = new Label();
        errorLabel.setStyle("-fx-text-fill: red;");
    
        Button simpan = new Button("Simpan");
        simpan.setOnAction(e -> {
            String nama = textField.getText();
            String umur = umurField.getText();
    
            if (nama.isEmpty() && umur.isEmpty()) {
                errorLabel.setText("Nama dan Umur tidak boleh kosong.");
                return;
            }else if(nama.isEmpty()){
                errorLabel.setText("Nama tidak boleh kosong.");
                return;
            }else if(umur.isEmpty()){
                errorLabel.setText("Umur tidak boleh kosong.");
                return;
            }
    
            boolean nameExists = false;
            for (String profile : profiles) {
                if (profile.split(",")[0].equals(nama)) {
                    nameExists = true;
                    break;
                }
            }
    
            if (nameExists) {
                errorLabel.setText("Nama sudah ada. Silakan gunakan nama lain.");
            } else {
                try {
                    int age = Integer.parseInt(umur);
                    if (age < 0) {
                        throw new NumberFormatException();
                    }
                    String profile = nama + "," + age;
                    profiles.add(profile);
                    home();
                } catch (NumberFormatException ex) {
                    errorLabel.setText("Umur harus berupa angka");
                }
            }
        });
        simpan.setPrefWidth(75);
    
        Button kembali = new Button("Kembali");
        kembali.setOnAction(e -> home());
        kembali.setPrefWidth(75);
    
        HBox inputNama = new HBox(10, namaLabel, textField);
        inputNama.setAlignment(Pos.CENTER);
    
        HBox inputUmur = new HBox(10, umurLabel, umurField);
        inputUmur.setAlignment(Pos.CENTER);
        inputUmur.setPrefHeight(50);
    
        HBox tombol = new HBox(170, kembali, simpan);
        tombol.setAlignment(Pos.CENTER);
    
        VBox addProfileScene = new VBox(10, profileIcon, inputNama, inputUmur, errorLabel, tombol);
        addProfileScene.setAlignment(Pos.CENTER);
        addProfileScene.setStyle("-fx-background-color: #dabfde;");
    
        stage.setScene(new Scene(addProfileScene, 400, 500));
        stage.setTitle("Tambah Profile");
    }
    
    private void profileScene(){
        Label profileLabel = new Label("Profile");
        profileLabel.setStyle("-fx-font-size: 20px; -fx-font-weight: bold;");
        
        VBox profileScene = new VBox(20, profileLabel);
        profileScene.setAlignment(Pos.CENTER);
        profileScene.setStyle("-fx-background-color: #c8a2c8;");
        
        for(String profile : profiles){
            String nama = profile.split(",")[0];

            HBox profileBox = new HBox(10);
            profileBox.setAlignment(Pos.CENTER_LEFT);
            
            ImageView profileIcon = new ImageView(new Image("file:/home/lev/Downloads/profilIcon.png"));
            profileIcon.setFitWidth(50);
            profileIcon.setPreserveRatio(true);

            Button btnprofile = new Button(nama);
            btnprofile.setOnAction(e -> tampilanProfile(profile));
            profileBox.getChildren().addAll(profileIcon, btnprofile);

            profileScene.getChildren().add(profileBox);
        }

        ScrollPane scroll= new ScrollPane();
        scroll.setContent(profileScene);
        scroll.setFitToWidth(false);
        scroll.setStyle("-fx-background: #c8a2c8;");
        
        Button kembali = new Button("Kembali");
        kembali.setOnAction(e -> home());
        kembali.setPrefWidth(75);

        HBox tombol = new HBox(kembali);
        tombol.setAlignment(Pos.BOTTOM_RIGHT);  
        
        VBox mainlayout = new VBox(20, profileLabel, scroll, kembali);
        mainlayout.setAlignment(Pos.CENTER);
        mainlayout.setStyle("-fx-background-color: #c8a2c8;");

        
        stage.setScene(new Scene(mainlayout,  400, 500));
        stage.setTitle("Daftar Profile");
    }

    private void tampilanProfile(String profile){
        ImageView fotoProfil = new ImageView(new Image("file:/home/lev/Downloads/cing.jpeg"));
        fotoProfil.setFitWidth(100);
        fotoProfil.setPreserveRatio(true);
        
        String[] detailprofil = profile.split(",");

        Label profileLabel = new Label("Profile " + detailprofil[0]);
        profileLabel.setStyle("-fx-font-size: 15px; -fx-font-weight: bold;");
        
        Label namaProfileLabel = new Label("Nama: " + detailprofil[0]);
        Label umurProfileLabel = new Label("Umur: " + detailprofil[1]);

        Button kembali = new Button("Kembali");
        kembali.setOnAction(e -> profileScene());
        kembali.setPrefWidth(75);

        HBox tombol = new HBox(kembali);
        tombol.setAlignment(Pos.CENTER);
        
        VBox profileScene = new VBox(10, profileLabel, fotoProfil, namaProfileLabel, umurProfileLabel, tombol); 
        profileScene.setAlignment(Pos.CENTER);
        
        profileScene.setStyle("-fx-background-color: #c8a2c8;");
        
        stage.setScene(new Scene(profileScene,  400, 500));
        
    }

    public static void main(String[] args) {
        launch();
    }

}